# Generated by Django 3.0.6 on 2020-05-30 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200530_2139'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='category',
            index_together={('parent', 'slug')},
        ),
    ]
