# Generated by Django 3.0.6 on 2020-05-31 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200530_2324'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='category',
            index_together={('parent', 'slug')},
        ),
    ]
